### ISSUE TITLE
create django model for riss data

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/connect#106]

**Comment by grillazz** [comment]
#110 #111 #112 lgacode available on /health_faclities/ and /api/facility/

**Comment by janetbutts** [comment]
Evenly split between jakub and francesco

**Comment by danse** [comment]
@grillazz closed this with https://github.com/eHealthAfrica/connect/pull/150

**Comment by danse** [comment]
who is `ehealthafrica-machine`?

**Comment by futuresandwich** [comment]
Ha, me apparently. Obviously should remove that account.
