### ISSUE TITLE
Data cleaning pipeline

### ISSUE THREAD

**Issue by lucychambers** [eHealthAfrica/connect#114]
This will not be part of MVP, but a wish has been expressed to automate the data cleaning pipeline from ODK collect -> Kano Connect dashboard to remove need for manual work.

**Comment by lucychambers** [comment]
Will have this for one or two alerts

**Comment by grillazz** [comment]
@danse this part of code https://github.com/grillazz/connect/blob/master/kano_konnect/etl/load_json_into_model.py is showin how i loading your json file into RissAlerts model here https://github.com/grillazz/connect/blob/master/kano_konnect/app/models.py#L241.
Fell free to updated model etc, if you need,

**Comment by danse** [comment]
thanks @grillazz, so i will add the importing script under `etl`. after i will do it, there will be still no logic in place to automate the executions of these scripts, right? they will still need to be run manually, or with a cron job

**Comment by grillazz** [comment]
yeah next we need to decide how we want to automate them. cron, django-celery or any other scheduler

**Comment by grillazz** [comment]
i still need to pick one for other loaders - so Im open for suggestions.

**Comment by danse** [comment]
this can have some impact on deployment, so we should ask the devops

**Comment by grillazz** [comment]
can you ?

**Comment by danse** [comment]
Quoting from Slack

> @grillazz, @filip, @norbert, @tiarnan, @lutz: we will need periodical tasks to be executed for Kano Connect, a python project based on Django. any suggestion, recommendation, requirement which might affect our choice? the main alternatives currently seem to be Celery or Cron
> 
> norbert [11:07 AM] 
> only cron
> 
> norbert [11:08 AM]
> way more reliable than Celery for scheduled tasks and way fewer moving parts that can fall over
> 
> francescoocchipinti [11:11 AM] 
> @norbert allright, is there a standard way to include snippets of cron files in the repo, in order to play nicely with deployment? also ... should we reference a specific version of cron?
> 
> norbert [11:12 AM] 
> depends on how it's deployed right now and how it'll be deployed in the future
> 
> francescoocchipinti [11:12 AM] 
> the project is not in production yet, as far as i know
> 
> norbert [11:13 AM] 
> the best way for now is probably to document all the necessary tasks and their schedules, or just put an example crontab somewhere in the repo
> 
> norbert [11:13 AM]
> then we'll install the actual crontab with Ansible
> 
> francescoocchipinti [11:13 AM] 
> cool
> 
> francescoocchipinti [11:14 AM]
> last thing ... usually python projects require a virtual environment to be enabled ... i guess that this could be a first step in the cron command, it does not sound so elegant though
> 
> francescoocchipinti [11:14 AM]
> anyway, let us not overcomplicate things ... cron will be, for now, we will eventually find solutions for more specific problems

**Comment by danse** [comment]
> filip
> @francescoocchipinti: just use `path/to/your/virtualenv/bin/python path/to/your/code.py` when executing. that uses the virtualenv. (edited)
> 
> norbert [11:25 AM] 
> yeah we already have some cron jobs that use a venv
> 
> norbert [11:25 AM]
> works fine
