### ISSUE TITLE
[Supervisions] RISS tab - guidance text

### ISSUE THREAD

**Issue by lucychambers** [eHealthAfrica/connect#121]
I think it would be nice to add some guidance text, to tell people how to interpret the information they are seeing. 

Suggest minor change to title and inserting this text at the top of the page: 

# Percentage of Health Facilities which conducted all planned supervisions.

## How to read this report: 

Report groups the health facilities by Local Government Area (LGA) code. 

* All LGAs with a red bar in the % complete column are below target for number of supervisions conducted. 
* All LGA with a blue bar under % complete column are on target for number of supervisions conducted. 

## Filter the report 

Click on any column header to filter by that column.

**Comment by grillazz** [comment]
@lucychambers maybe we should add 90% target value in description ?

**Comment by lucychambers** [comment]
Good call. Something like.

"The target value is currently: 90%."
