### ISSUE TITLE
Login Errors 

### ISSUE THREAD

**Issue by lucychambers** [eHealthAfrica/connect#123]
Kat is experiencing errors in logging in to Kano Connect. 

When she clicks - login via Google, she is told her username and email are taken and there is no way to circumvent. [Screenshot](https://drive.google.com/open?id=0B40AhgsIbVk2eEs0bFVOaXJuMnM&authuser=0)

Neither Francesco and I can replicate as we are not asked for our username or email. 

If Kat clicks "Forgot Password", she gets [this error message](https://drive.google.com/open?id=0B40AhgsIbVk2bUloQ1dSWF8xaDA&authuser=0)

**Comment by janetbutts** [comment]
My flight was canceled, but I will be back in Kano tomorrow. If no one can
trouble shoot by then, I can work with her tomorrow.

**Comment by danse** [comment]
@janetbutts wrote

> I deleted Kat's account, then had her register again. she is able to log in

**Comment by grillazz** [comment]
are we ok to close it ?

**Comment by janetbutts** [comment]
Yes, let's close and see if the issue comes up again since everyone else
was able to use google auth.

Best Regards,
Janet Butts
Project Manager
eHealth Africa
*www.ehealthafrica.org <http://www.ehealthafrica.org/>*
mobile: +234 909 513 8249
