### ISSUE TITLE
Improvements for the presentation of an indicator

### ISSUE THREAD

**Issue by danse** [eHealthAfrica/connect#124]
The prototype related to the indicator *Percentage of Health Facilities which conducted all planned supervisions* implemented according to ticket #109 triggered some ideas for improvements, which we want to reconsider once we will have more alerts implemented.

Here i quote the ideas @lucychambers wrote on the original ticket:

> [Mockup v2](https://drive.google.com/open?id=0B40AhgsIbVk2TTdPOVc4WEFySVE&authuser=0)
> 
> Features that would be nice to have: 
> 
> * Highlight on the navigation tab which is selected so it is easier to see that you are viewing the RISS reports vs others. 
> * ** Would also be great if the *default* view of the page had the facilities which were underperforming highlighted.**

**Comment by lucychambers** [comment]
Won't fix - can deal with enhancements later.
