### ISSUE TITLE
[RISS][Details Tab] Add new alert types to stream

### ISSUE THREAD

**Issue by lucychambers** [eHealthAfrica/connect#127]
* Number of HFs that reported non-availability of data tools
* Percent of HFs supervised which conducted all planned fixed sessions
* Percent of HFs supervised which did not hold the planned session  on the previous month
* Number of zonal cold stores with adequate cold chain capacity

Outcome will be a prototype with multiple types of alerts. 

Believe decision was to go with one page for now to see how they look.

**Comment by lucychambers** [comment]
One way of presenting this would be to have it purely as a text list. If the facility triggers an alert - it is phrased as a text phrase. 

We have some phrased as 'number of' X and some phrased as 'proportion'. 

# Proportion / Percentage

For now, let's leave ones which are phrased as 'proportion' as charts - though I think we might want to change them later.  

# Number

For ones which have number in the title - we could do the following. Use an entire phrase to represent exactly what the problem is - which means the data can be easily understood. 

So the pattern of text we could use would be: 

[Name of entity [LGA]] [metric][time period] 

Example: 

[In red] 
Albasu did not hold the planned session on the previous month. 

We could use the [bootstrap alerts](http://getbootstrap.com/components/#alerts) if that would simplify things. 

![screen shot 2015-05-27 at 12 45 29](https://cloud.githubusercontent.com/assets/1029861/7834310/4a1c9bea-046e-11e5-8251-ae85e96128db.png)

- 

Could you integrate one of the alerts which is framed as 'number' - and we can see what it looks like? I have a suspicion that they might be clearer eventually and we might want to convince people to reframe the indicators. 

See also Francesco's comments in slack about 100% needing to be red for the bar charts - the negatives confused me!

**Comment by grillazz** [comment]
ok i read this and try to deliver it. @lucychambers if you have some mockups ready pls let me know

**Comment by lucychambers** [comment]
Could we try something like this to start off with? 

https://drive.google.com/open?id=0B40AhgsIbVk2c0xhcXBxVGozRTg&authuser=0

(Apologies - for some reason, they won't let me upload the image here)

**Comment by lucychambers** [comment]
My belief is that we have 2/4 of these implemented - correct?

**Comment by grillazz** [comment]
well we have what is on page :)

**Comment by lucychambers** [comment]
Will close this as believe we will work on it as part of #169
