### ISSUE TITLE
allow write-access for lomis to export facility UUID into KC facility data

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/connect#130]

**Comment by grillazz** [comment]
PUT http://connect.kano.org.ng/api/facility_update/

**Comment by janetbutts** [comment]
waiting for feedback from femi in lomis that he is able to write uuid to kc database

**Comment by grillazz** [comment]
GET and PUT working example http://connect.kano.org.ng/api/facility_update/kns-mkk-kgn-102/
