### ISSUE TITLE
[RISS] Filter alerts by different indicator name

### ISSUE THREAD

**Issue by lucychambers** [eHealthAfrica/connect#142]
* Ability to filter by indicator - so we may want to give each indicator names / numbers

**Comment by janetbutts** [comment]
dependency on 127

**Comment by lucychambers** [comment]
See comment about multiple tags in #144

**Comment by lucychambers** [comment]
Pending #183

**Comment by grillazz** [comment]
think this is done right ? we have filter by alert id which is equal to indicator names/numbers ?

**Comment by lucychambers** [comment]
Yes, we do. There are currently only LG alerts in there but not sure if
that is because they are not loaded...
