### ISSUE TITLE
Adapt the alert data model

### ISSUE THREAD

**Issue by danse** [eHealthAfrica/connect#148]
The alert data model has to be adjusted so that:

- [x] it supports alerts about lack of data
- [x] it supports alerts at different levels
- [x] it has a valid key. the current one does not provide unicity
- [x] it includes a date, in order to show alerts sorted by date

Me and @grillazz will probably need to collaborate on this

This ticket might need to be splitted.

About point 3, with the current key i got the following error:

    Key (alert_id, lgacode, value)=(3, 20042, 0.666666666666667) already exists.

But we can totally have multiple alerts with same type, area and value

**Comment by danse** [comment]
2 and 3 are necessary for the milestone, 4 would be nice to have for the milestone

**Comment by janetbutts** [comment]
@grillazz , let me know what is needed in terms of a new ticket after you and @FrancescoK collaborate.

**Comment by FrancescoK** [comment]
@janetbutts I think you mean @danse (Francesco O.) :)
