### ISSUE TITLE
[RISS] Workflow to dismiss alerts 

### ISSUE THREAD

**Issue by lucychambers** [eHealthAfrica/connect#166]
As Maryam
I want to be able to acknowledge alerts which appear in my alert feed
So that I can easily see which alerts are new and require actioning 

Feature: Ability to mark alerts as acknowledged 
Secondary feature: ability to feature by new (i.e. neither acknowledged nor resolved), acknowledged  with a view defaulting to 'new'. 

![journal - 8](https://cloud.githubusercontent.com/assets/1029861/8102537/1eed6bca-1021-11e5-9a65-d75edd523901.png)

And if the X is selected on alert 1, and 'Show' filter is set to the default of 'new only'. Alert 1 will simply disappear. 

![journal - 9](https://cloud.githubusercontent.com/assets/1029861/8102563/516ba2e2-1021-11e5-99d7-88580fc1ee35.png)

**Comment by grillazz** [comment]
updated size b/c missed rest api change in development planning
