### ISSUE TITLE
[RISS] Add current status page to the navigation

### ISSUE THREAD

**Issue by lucychambers** [eHealthAfrica/connect#182]
We need a separate page from the alerts page for the monitoring view. This should be a subpage of the RISS tab and easy to navigate to and from from the alerts page. 

Will do sketches later.

**Comment by lucychambers** [comment]
Required for #133

**Comment by danse** [comment]
As far as i remember this is just about adding the page in the navigation bar

**Comment by lucychambers** [comment]
Yep it is, if you don't need tickets this granular, we can close it. 

I don't think this wants to go in the actual navigation, but one step below. Navigation is already quite crowded - so think this should be a dropdown. 

![journal - 8](https://cloud.githubusercontent.com/assets/1029861/8279974/28449a48-18d9-11e5-827b-746566f34a65.png)

* C. status should be written in full - current status, just couldn't fit on my drawing!
* Clicking the top level RISS tab should also default to the current status overview

**Comment by danse** [comment]
It is not an accident that the navigation is so crowded. Typical symptom of a lack of coherent design and a precise goal

**Comment by lucychambers** [comment]
Can I now reassign this @danse @grillazz? I think this will go with pull request #133 to integrate the current status page.

**Comment by danse** [comment]
We agreed with @grillazz that he can do this, while i am trying to finish #202 which blocks other tickets

**Comment by lucychambers** [comment]
Remove: 

* Home 
* Report

**Comment by grillazz** [comment]
as quick fix adding RISS Overview to main menu
