### ISSUE TITLE
[RISS] Add new text based alerts based of newly available alerts 

### ISSUE THREAD

**Issue by lucychambers** [eHealthAfrica/connect#183]
Closure of #169 should enable new text based alerts to be added to the system. 

Higher priority than #144, #142, #166 as we can get feedback from the board on how they are framed as soon as they can see what the alerts really look like!

**Comment by grillazz** [comment]
alert_id need to be properly loaded and matched with alert ids in RISS Indicators spredsheet

**Comment by danse** [comment]
@grillazz done with https://github.com/eHealthAfrica/connect/pull/187, reassigning to you
