### ISSUE TITLE
[RISS][Cosmetic Change] Use bootstrap for the alerts 

### ISSUE THREAD

**Issue by lucychambers** [eHealthAfrica/connect#197]
It would be a better user experience to use bootstrap for the positioning of the crosses. e.g. : 

![screen shot 2015-06-18 at 16 39 04](https://cloud.githubusercontent.com/assets/1029861/8233820/90040f5a-15d8-11e5-9668-2826c82a25bb.png)

![screen shot 2015-06-18 at 16 40 18](https://cloud.githubusercontent.com/assets/1029861/8233852/df8b50ec-15d8-11e5-93ab-d80bb89717b3.png)

This way, the cross will always appear at the right hand side of the user interface no matter the size of the screen- so the person can just move mouse down and not search for them.

**Comment by grillazz** [comment]
@lucychambers: Not only cosmetic change. B/c there was backbone part to eliminate AngularJS and replace it with jQuery which is playing well with Bootstrap 3 to have dismiss alert functionality available with REST API etc. Mostly taks was done. Part which left is REST API and page permissions setup and persistent filters with jQuery.

**Comment by lucychambers** [comment]
Thanks @grillazz - I will split that into a new ticket
