### ISSUE TITLE
[RISS] Include proper due date management

### ISSUE THREAD

**Issue by danse** [eHealthAfrica/connect#202]
Currently, we are just considering the last 30 days, which is wrong. We want:

- alerts and statuses are reset on the due date
- alerts and statuses correctly express data related to the last period

**Comment by janetbutts** [comment]
Waiting on Kat to provide date statuses.

**Comment by danse** [comment]
I implemented this using the 15th of the month for every level, but the code allows to easily change this in the future

**Comment by danse** [comment]
for the moment i will keep generating alerts at every data import, in order for us to design the feature easier. i created #225 in order to eventually generate alerts just when passing the submission date
