### ISSUE TITLE
Deploy KC on new development server

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/connect#215]

**Comment by lucychambers** [comment]
@grillazz - do we have the new dev server?

**Comment by grillazz** [comment]
no yet @lucychambers

**Comment by lucychambers** [comment]
Is anything blocking, or just no time?

**Comment by grillazz** [comment]
just no time - if it is priority number one i can switch and try to deploy KC onto new dev

**Comment by lucychambers** [comment]
Nope - just checking as I have the opportunity to ask for Devops support
today, so let me know if anything would be helpful here!

**Comment by grillazz** [comment]
Well they did everything what i requested for :)

**Comment by grillazz** [comment]
production server was moved to new host http://connect-d2.ie.connect.kano.org.ng/

**Comment by lucychambers** [comment]
So can this be closed @grillazz ?

**Comment by grillazz** [comment]
think yes @lucychambers but we need two separate tickets in backlog for stage and dev servers setup

**Comment by lucychambers** [comment]
Closing, replaced by #246 and #247
