### ISSUE TITLE
Make sure all alerts appear in filter list

### ISSUE THREAD

**Issue by lucychambers** [eHealthAfrica/connect#233]
Currently only lga alerts appear in the list even though we clearly have others in the system: 

![screen shot 2015-07-01 at 12 19 52](https://cloud.githubusercontent.com/assets/1029861/8452510/d69ce06e-1feb-11e5-9441-dd994677018f.png)

Include alert even if it is not triggered. If no alerts appear for the selected filters display text: "There are no alerts available for your selected filters"

**Comment by lucychambers** [comment]
@grillazz @danse - can I now reassign this to one of you?

**Comment by grillazz** [comment]
@lucychambers I will take care of it
